### ISSUE TITLE
这个键盘真不错，建议可以通过键盘左右键切换去选字

### ISSUE THREAD

**Issue by ztxcyk** [justdoit-mqr/softkeyboard#1]
输入拼音后，下面会出来待选择的字，需要用鼠标去点击。如果可以通过键盘左右键控制选中就更好了。

**Comment by justdoit-mqr** [comment]
哈哈，刚看到。这个项目主要是针对嵌入式显示屏没有外接键盘写的，所以当时就没有考虑这方面功能。

**Comment by justdoit-mqr** [comment]
> 输入拼音后，下面会出来待选择的字，需要用鼠标去点击。如果可以通过键盘左右键控制选中就更好了。

哈哈，刚看到。这个项目主要是针对嵌入式显示屏没有外接键盘写的，所以当时就没有考虑这方面功能。

**Comment by justdoit-mqr** [comment]
> 输入拼音后，下面会出来待选择的字，需要用鼠标去点击。如果可以通过键盘左右键控制选中就更好了。

哈哈，刚看到。这个项目主要是针对嵌入式显示屏没有外接键盘写的，所以当时就没有考虑这方面功能。
